version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vervemartimg
    ports:
      - "4000:4000"  # Expose the port for your Node.js application
    env_file:
      - .env  # Load environment variables from the .env file

  db:
    image: postgres:latest
    environment:
      DB_CONNECTION_URL: ${DB_CONNECTION_URL}
      JWT_SECRET: ${JWT_SECRET}
      
